package org.brms.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String firstName;
   private java.lang.String lastName;
   private java.lang.Integer hourlyRate;
   private java.lang.Integer wage;

   public Person()
   {
   }

   public java.lang.String getFirstName()
   {
      return this.firstName;
   }

   public void setFirstName(java.lang.String firstName)
   {
      this.firstName = firstName;
   }

   public java.lang.String getLastName()
   {
      return this.lastName;
   }

   public void setLastName(java.lang.String lastName)
   {
      this.lastName = lastName;
   }

   public java.lang.Integer getHourlyRate()
   {
      return this.hourlyRate;
   }

   public void setHourlyRate(java.lang.Integer hourlyRate)
   {
      this.hourlyRate = hourlyRate;
   }

   public java.lang.Integer getWage()
   {
      return this.wage;
   }

   public void setWage(java.lang.Integer wage)
   {
      this.wage = wage;
   }

   public Person(java.lang.String firstName, java.lang.String lastName,
         java.lang.Integer hourlyRate, java.lang.Integer wage)
   {
      this.firstName = firstName;
      this.lastName = lastName;
      this.hourlyRate = hourlyRate;
      this.wage = wage;
   }

}